_target_: watchmal.engine.regression.MultiTaskRegressionEngine
target_key: ['positions','directions','energies']
target_scale_factor: 
    positions: 4000
    directions: 1
    energies: 2000
target_scale_offset:
  positions: 0
  directions: 0
  energies: 0

