gpu_list:
  - 0
  - 1
seed: 1111
dump_path: './outputs/'
model:
  num_output_channels: 1
defaults:
  - data: hk_split
  - data/dataset: hk_cnn
  - model: resnet152_momentum
  - engine: regression_momentum
 # - tasks/restore_state: restore_state_momentum
  - tasks/train: train_transformer  
  - optimizers@tasks.train.optimizers: adamW_momentum
  - scheduler@tasks.train.scheduler: cosinelr
  - loss@tasks.train.loss: huber_momentum
  - sampler@tasks.train.data_loaders.train.sampler: subset_sequential
  - sampler@tasks.train.data_loaders.validation.sampler: subset_sequential
  - _self_

