gpu_list:
  - 0
  - 1

seed: 1111
dump_path: './outputs/'
model:
  num_output_channels: 3
defaults:
  - data: hk_split
  - data/dataset: hk_cnn
  - model: resnet152_direction
  - engine: regression_direction
 # - tasks/restore_state: restore_state_direction
  - tasks/train: train_resnet  
  - optimizers@tasks.train.optimizers: adam_direction
  - loss@tasks.train.loss: huber_direction
  - sampler@tasks.train.data_loaders.train.sampler: subset_sequential
  - sampler@tasks.train.data_loaders.validation.sampler: subset_sequential
  - _self_
