_target_: watchmal.loss.uncertainty_loss.UncertaintyLoss

task_losses:
  positions:
    _target_: watchmal.loss.position_huber.PositionHuberLoss
    delta: 0.15                            
  directions:
    _target_: watchmal.loss.direction_huber.DirectionHuberLoss 
    delta: 0.001
  energies:
    _target_: watchmal.loss.relative_huber.RelativeHuberLoss
    delta: 0.07                           

initial_variances:
    positions: 1
    directions: 1
    energies: 1
